= WISE WORDS OF RAGNAR REDBEARD

* You can talk of "human brotherhood" until you're black and blue; +
no law of heaven or earth, or hell, can ever make it true.

* If one man smites you on the cheek, +
don't turn the other soft and meek, +
but smash him back and lay him low. +
war for war, and woe for woe.

* What are men but hungry wolves, a prowling on the heath? +
if in a pack of wolves you hunt, you'd better sharp your teeth.

* O some must watch +
and some must sleep +
and some must perish slowly; +
and some must weep +
and some must reap, +
till all things go to glory.”

* Poison lurks in pastor preachments, +
Satan works through golden rules, +
Hell is paved with law and justice. +
Christs were made to fetter fools.

* Life is strife for every man, +
For every son of Thunder; +
Then be lion, not a lamb +
And don't be trampled under +
+
"Christ is my redeemer", — +
I heard men rave and shout, +
But where is their "redemption"? +
What is it all about? +
+
A painted idol on a tree — +
Dripping tears and gore — + 
A painted idol is to me — +
And it is nothing more. +
+
Dogmas base — and wicked gospels, +
Treacherous logic — shallow learning, +
Prophets false — insane immortals +
And coward theories of discerning. +
+
Carve a wooden image, +
Daub it o'er with paint, +
And straightway it is a sacred thing, +
A Godess — Saviour — Saint.

* The "will to live" +
Is king of kings. +
And "gold and iron" +
Is Lord of Things.

* In the balance weighed and wanting, +
The evil reign of Christ is o'er, +
2,000 years of hell condemn him +
He shall crush our souls no more.

* For strife and struggle +
Man is born; +
But sheep and lambs +
Are always shorn.

* There is no Jew Jehovah +
Commanding things on high; +
There is no golden heaven +
To go to when you die;

* In your own heart +
Is all the law. +
Beware of Christ, +
That man of straw

* To bleat and pray, +
And live like clods, +
Is not the way, +
Of men or gods.

* There is no Blessed Saviour +
For two and two are four, + 
And the gospel tale is fiction, +
Fiction, fiction, nothing more.

* Live and love and take and give. +
And laugh and fight and sigh; +
For, it's all there is of life to live, +
And all of death to die.

* Now is your appointed time, +
This very hour and day, +
To love and laugh and feast and fight. +
And LIVE before you're grey.

* All hail the power of Israel's name,  +
Let nations prostrate tall, +
Bring out the royal diadem +
And crown him lord of all.

* Statesmen mock and swindle, +
And judges work you woe, +
Laws are the snares of Satan +
And Christ's your mortal foe.

* THE TRUE RELIGION
    ** If one man smite you on the cheek, +
    Don't turn the other, soft and meek, +
    But smash him back, and lay him low, +
    War for war, and blow for blow.

* IDOLS
  ** Some carve their idols out of stone +
  (Monsters fierce and rude). +
  Some hew them in the shape of beasts +
  From solid blocks of wood.
+
Some deck them out in gems of price, +
With diadems and crowns: +
Some dust red ochre on their cheeks, +
And give them skirts and gowns.
+
Some paint them bold, strong and free, +
With grace in every line; +
Some make them evil things to see, +
That bleed and weep and whine. 
+
But, the idol gods of Christendom, +
Their glory never fails; +
A Hebrew maid — a Hebrew babe +
And — A BOOK OF HEBREW TALES.

* Heathens in their blindness +
Bow down to wood and stone +
AN idol made of printers ink +
We holy Christians own

* AN IRON IDOL
  ** THOU FLAMING IDOL, +
  TOWERING HIGH. +
  WHAT ART THOU +
  BUT — AN IRON LIE! +
  HEART OF STONE +
  AND EYES OF GLASS, +
  FEET OF CLAY +
  AND WOMB OF BRASS.  +
  FALSE IN THEORY, +
  FACT AND FAME, +
  A BRAZEN MONSTER +
  CROWNED WITH FLAME.

* SURVIVAL
  ** The force that made the iron grow, +
Gives weakness no protection. +
It bids us battle down the foe, +
Its logic is “Selection.”
+
It shakes the nations in a sieve, +
Each one must meet a rival, +
And chooseth from the strong that live. +
The strongest for “Survival”.

* THE GOD OF ALL OUR WAYS
  ** The government — the government. +
It shears us night and day — +
It taxes us and taxes us, +
And steals our wealth away. +
With bond and debt it loads us down. +
By cunning, craft and skill, +
And puts its bullets in the heart +
Of those who cross its will.
+
O, government — the government — +
In air and sea and earth, +
Its slightest nod is law and god, +
Its judge of life and death.
+
So we must crouch to government,  +
With body, mind and soul, +
And keep our tongue between our teeth, +
While it collects its toll.
+
O, government — the government — +
It eats up mine and thine — +
The Beast of Blood and seven horns — +
The Dragon of the Slime.
+
To thee, O, blessed government +
We chant glad songs of praise, +
Thou holy sacred Juggernaut +
Lord God of all our ways.

* ODIN'S SONG
  ** I am the strife God — +
I am the Peace Destroyer — +
Struggle is my gospel — +
Spears my apostles
+
Over high mountains — +
Through green valleys — +
In and out of nations — +
Night and day I journey.
+
From the isles of Yonder — +
Across bleak icy oceans — +
High on storm steeds — +
Astride of cloud wheels.
+
To all sons of women — +
I bring high tidings — +
To the brave-born, gladness — +
To dastards, weeping.
+
Unceasing I cry out — +
Bold be and mighty — +
Gold hoards are bulging — +
Be best and strongest.
+
East and west I wander — +
North and south I travel — +
I, the Flame Messiah — +
The Joyful Idol smasher.
+
I, the freedom-bringer — +
I, the Babel-burner — +
I, the Flaming-Angel — +
Red in tooth and Claw.
+
I, the deed propounder — +
Choosing one-or-millions — +
I, all the Christs defiant — +
Lord of Ignis Ardens.

* TRUST IN YOURSELF! BELIEVE YOU ARE RIGHT!
  ** Let lions cease to prowl and fight, +
Let eagles clip their wings, +
Let men of might give up their right, +
The foolish poet sings. +
+
Let lords of gold and +
Caesars bold, +
For ever pass away, +
Enrich the slaves; enthrone the knaves, +
The base-born prophets say.
+
But I maintain with hand and pen +
The other side of things +
The bold man's right to rule and reign +
The way of gods and kings.
+
So capture crowns of wealth and power +
(If you've the strength and can), +
For strife is life's eternal dower, +
And nothing's under ban.
+
Ye, lions wake and hunt and fight, +
Ye, eagles, spread your wings; +
Ye, men of might, believe you're right. +
For you indeed are kings.

* THE CONQUERORS
  ** I sing the song of the valiant, +
In the wars of the bond and free, +
Who take the world as they find it, +
And marvel at men like we.
+
With eyes in their heads to see with +
Brains in their skulls to think, +
And, reckless of gods and devils, +
They're never the first to sink.
+
They've scorned the laws and prophets, +
Since ever the world began, +
And laughed at the fearsome idols, +
Messiahs and Books and Man.
+
Trust not empire, nor republic, +
Trust not school or church or throne, +
Trust not anarch, priest or statesman, +
Trust in yourself and DARE alone.
+
Undaunted live, undaunted perish, +
Do and die, but make no moan; +
Be proud and bold, high valor cherish, +
Be thine own God, and THINK alone.
+
Failure to seize subsistence, +
Is proof that you are "unfit" +
And, toil for a bare existence, +
That, that is the "bottomless pit".

* Rejoice and halleluia +
And bend the lowly knee +
Glory, laud and honor +
To God of Gallilee

* Some worship gods of wood and stone +
And gods of clay and brass, +
And bulls and snakes, and rams and lambs +
And She-gods too, alas!
+
But the God we own, the Wonderful, +
He doth them all surpass — +
An Asiatic yellow man +
A Hebrew on an ASS

* That image spiked upon a cross, +
That varnished idol hung so high, +
And do you think that God is there? +
Why then, methinks, you think a Lie. +
+
You can pray until you're toothless, +
And vote and whine and shout, +
But laws of life are ruthless, +
And you shall find it out